### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by huzhenjie** [GLGJing/ScreenRecorder#2]
Here will case `ArrayIndexOutOfBoundsException` in `MainActivity`

```
if (grantResults[0] != PackageManager.PERMISSION_GRANTED) {
```

> exception

```

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.glgjing.recorder, PID: 12158
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.glgjing.recorder/com.glgjing.recorder.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                   Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                      at com.glgjing.recorder.MainActivity.onRequestPermissionsResult(MainActivity.java:87)
                      at android.app.Activity.requestPermissions(Activity.java:4116)
                      at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompat23.java:32)
                      at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:316)
                      at com.glgjing.recorder.MainActivity.onCreate(MainActivity.java:59)
                      at android.app.Activity.performCreate(Activity.java:6664)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6077) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 

```

**Comment by borjaruiz** [comment]
If request is cancelled, the result arrays are empty, so you must put another condition in the if:

f (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED)

**Comment by huzhenjie** [comment]
@borjaruiz :

I known how to fix it .

But I hope that the code owner can fix it in the project.
