### ISSUE TITLE
stop error

### ISSUE THREAD

**Issue by songsh** [GLGJing/ScreenRecorder#3]
java.lang.RuntimeException: stop failed.
at android.media.MediaRecorder.stop(Native Method)
the saved mp4 can not play.

**Comment by Duanyangyu** [comment]
same error.

**Comment by wyj3531** [comment]
java.lang.RuntimeException: stop failed.
at android.media.MediaRecorder.stop(Native Method)
the saved mp4 can not play.

**Comment by HappyMiao** [comment]
这个问题你们解决了吗，求教

**Comment by jingmaolin** [comment]
The Error just because of : mediaRecorder.setVideoSize(width, height)
The width and height can not simply use the screen's width and height ,
the width and height should use the values which are  supported by the camera of the device.

**Comment by ManonX5** [comment]
@jingmaolin Great!
